<?php

return [
    'default_currencies'     => 1,
    'type_logo'     => 'assets/images/logo-icon.png',
    'type_name'     => 'RuAds',
    'cms_title'     => 'Buy and Sale',
    'type_footer'     => 'All Copyrights Reserved @ 2021 - Developed by rumon',
    'type_mail'     => 'ruads@mail.com',
    'type_address'     => 'Vuter goli, Uportala, janina',
    'type_fb'     => 'facebook.com',
    'type_tw'     => 'facebook.com',
    'type_number'     => '8801685755707',
    'type_google'     => 'facebook.com',
    'footer_logo'     => 'uploads/site/footer-logo4857.png',
    'favicon_icon'     => 'assets/images/logo/favicon-icon.png',
    'footer_location' => '1420 West Jalkuri Fatullah,Narayanganj, BD',
    'footer_number' => 'support@classicads.com info@classicads.com',
    'footer_mail' => '+8801838288389 +8801941101915',
    'payment_image' => 'uploads/site/payment-image1849.png',
    'app_image' => 'uploads/site/app-image9284.gif',
    'type_linkedin' => 'linkedin',
    'type_youtube' => 'youtube',
    'type_pinterest' => 'pinterest',
    'type_instagram' => 'instagram',

    'login_image'     => 'assets/images/login/3.jpg',
    'meta_keys' => 'Nisi ut fugiat nequ',
    'meta_desc' => 'Ullam ducimus fugia',
    'meta_title' => 'Sint vel nobis ipsum',
    'newsletter' => 'off',
    'paginate' => '12',
    'pre_loader' => 'uploads/site/pre-loader3065.gif',
    'facebook_login_status' => 'Yes',
    'google_login_status' => 'Yes',
    'google_analytics_active' => 'Yes',
    'push_notify_active' => 'Yes',

    'multi_lang' => 'Yes',
    'multi_currency' => 'Yes',
];
